spring:
  datasource:
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
