spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/calendar
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000

oauth:
  kakao:
    auth_url: https://kapi.kakao.com/v2/user/me
  apple:
    auth-uri: https://appleid.apple.com/auth/keys

jwt:
  access-token:
    expire-length: 3600000
    secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecret
