spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/calendar
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false

oauth:
  kakao:
    auth_url: https://kapi.kakao.com/v2/user/me
  apple:
    auth-uri: https://appleid.apple.com/auth/keys
