spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/calendar
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false

oauth:
  kakao:
    auth_url: https://kapi.kakao.com/v2/user/me
  apple:
    auth-uri: https://appleid.apple.com/auth/keys

jwt:
  access-token:
    expire-length: 3600000
    secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecret

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: test
      media-url: test
      custom-endpoint: none
      dir: none

client-version:
  ios:
    required: 0.5.0
    latest: 1.0.0
  aos:
    required: 0.5.0
    latest: 1.0.0

app:
  default-calendar-id: e39fca26-a97a-4adc-acb4-db82e158c967
