spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phochak
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
