name: CI/CD-workflow

on:
  push:
    branches: ["qa"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'adopt-hotspot'
          java-version: '17'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew jib

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy AWS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          script: |
            sudo docker stop calendar_server
            sudo docker rm calendar_server
            sudo docker images | grep calendar-jib-dev | sort -k2 | awk '{if(NR>1) print $3}' | xargs sudo docker rmi --force
            
            sudo docker pull woojin8787/calendar-jib-dev:latest
            sudo docker rm calendar_temp
            sudo docker create --name calendar_temp -v /app woojin8787/calendar-jib-dev:latest
            
            sudo docker run -d --name calendar_server -v /home/ubuntu/logs:/logs -e TZ=Asia/Seoul \
            --network host --env-file /home/ubuntu/app/dev.env --volumes-from calendar_temp woojin8787/calendar-jib:latest
